#!/bin/bash
#
# if no vihicle name is given
# i.e. -z $1 is defined and it is Null
#
# if no command line arg
if [ -z $1 ]
then
  rental="*** Unknown vehicle ***"
elif [ -n $1 ]
then
  # otherwise make first arg as rental
  rental=$1
fi

case $rental in
  "car") echo "For $rental Rs. 20 per k/m";;
  "van") echo "For $rental Rs. 10 per k/m";;
  "jeep") echo "For $rental Rs. 5 per k/m";;
  "bicycle") echo "For $rental Rs. 20 paisa per k/m";;
  *) echo "Sorry, I can not cat a $rental for you";;
esac
