#!/bin/bash

# script to create simple menus and take actions according to that selected
# menu item

while :
  do
    clear
    echo "------------------------------"
    echo " Main Menu "
    echo "------------------------------"
    echo "[1] Show Todays date/time"
    echo "[2] Show files in current directory"
    echo "[3] Show calendar"
    echo "[4] Start editor to write letters"
    echo "[5] Exit/Stop"
    echo "==============================="
    echo -n "Enter your menu choice [1-5]: "
    read yourch
    case $yourch in
      1) echo "Tody is `date`, press a key ..." ; read ;;
      2) echo "Files in `pwd`"; ls -l ; echo "Pess a key .."; read ;;
      3) cal ; echo "Pess a key ..." ; read ;;
      4) nano ;;
      5) exit 0 ;;
      *) echo "Opss!!! Please select choice 1,2,3,4 or 5" ; read ;;
    esac
  done
  
# o `read` o final he para esperar um pouco ,  
# sem ele so mostra o menu
